version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@8.1.2
executors:
  my-executor:
    machine:
      image: ubuntu-2204:2022.04.1
jobs:
  build-push-image:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Docker-authenticate
          command: sudo docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
      - run:
          name: Docker-build
          command: sudo docker build -t $DOCKER_IMAGE_NAME:v1.0.<<pipeline.number>> .
      - run:
          name: Docker-push
          command: sudo docker push $DOCKER_IMAGE_NAME:v1.0.<<pipeline.number>>
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ECR_ACCESS_KEY
          aws-secret-access-key: AWS_ECR_SECRET_KEY
          registry-id: AWS_ECR_REGISTRY_ID
          repo: hello-hi-api
          public-registry: true
          tag: 'latest,v1.0.1-dev'
  buildpush-image:
    jobs:
      - build-push-image