version: 2.1
executors:
  my-executor:
    machine:
      image: ubuntu-2204:2022.04.1
commands:
  awscliconfigure:
    steps:
      - run: aws configure --profile superhero-ecr set aws_access_key_id $AWS_ECR_ACCESS_KEY
      - run: aws configure --profile superhero-ecr set aws_secret_access_key $AWS_ECR_SECRET_KEY
      - run: aws configure --profile superhero-ecr set region "us-east-1"
jobs:
  build-push-image:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Docker-authenticate
          command: sudo docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
      - run:
          name: Docker-build
          command: sudo docker build -t $DOCKER_IMAGE_NAME:v1.0.<<pipeline.number>> .
      - run:
          name: Docker-push
          command: sudo docker push $DOCKER_IMAGE_NAME:v1.0.<<pipeline.number>>
      - awscliconfigure
      - run: 
          name: AwsEcr
          command: aws ecr-public get-login-password --profile superhero-ecr --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - run:
          name: Docker-Aws-Tag
          command: sudo docker tag $DOCKER_IMAGE_NAME:v1.0.<<pipeline.number>> public.ecr.aws/g2p5t3u7/hello-hi-api:v1.0.<<pipeline.number>>
      - run:
          name: Docker-Aws-Push
          command: sudo docker push public.ecr.aws/g2p5t3u7/hello-hi-api:v1.0.<<pipeline.number>>
workflows:
  buildpush-image:
    jobs:
      - build-push-image